import { Patient, Appointment, DentalRecord, Service, User } from '@/types';

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1 (555) 123-4567',
    dateOfBirth: '1985-06-15',
    gender: 'Male',
    address: '123 Main St, Anytown, USA',
    emergencyContact: '+1 (555) 987-6543',
    bloodType: 'O+',
    allergies: ['Penicillin', 'Latex'],
    medicalHistory: ['Hypertension', 'Asthma'],
  },
  {
    id: '2',
    name: 'Emma Wilson',
    email: 'emma.w@example.com',
    phone: '+1 (555) 234-5678',
    dateOfBirth: '1992-03-22',
    gender: 'Female',
    address: '456 Oak Ave, Springfield, USA',
    emergencyContact: '+1 (555) 876-5432',
    bloodType: 'A-',
    allergies: ['Sulfa drugs', 'Nuts'],
    medicalHistory: ['Type 2 Diabetes'],
  },
  {
    id: '3',
    name: 'Robert Chen',
    email: 'r.chen@example.com',
    phone: '+1 (555) 345-6789',
    dateOfBirth: '1978-11-30',
    gender: 'Male',
    address: '789 Pine St, Riverdale, USA',
    emergencyContact: '+1 (555) 765-4321',
    bloodType: 'B+',
    allergies: ['Codeine'],
    medicalHistory: ['High Cholesterol', 'GERD'],
  },
  {
    id: '4',
    name: 'Maria Garcia',
    email: 'maria.g@example.com',
    phone: '+1 (555) 456-7890',
    dateOfBirth: '1990-07-14',
    gender: 'Female',
    address: '101 Maple Dr, Brookville, USA',
    emergencyContact: '+1 (555) 654-3210',
    bloodType: 'AB+',
    allergies: ['Aspirin', 'Iodine'],
    medicalHistory: ['Migraines'],
  },
  {
    id: '5',
    name: 'David Kim',
    email: 'david.kim@example.com',
    phone: '+1 (555) 567-8901',
    dateOfBirth: '1982-12-05',
    gender: 'Male',
    address: '202 Birch Ln, Hilltop, USA',
    emergencyContact: '+1 (555) 543-2109',
    bloodType: 'O-',
    allergies: ['Shellfish'],
    medicalHistory: ['Sleep Apnea', 'Anxiety'],
  },
  {
    id: '6',
    name: 'Sophia Patel',
    email: 's.patel@example.com',
    phone: '+1 (555) 678-9012',
    dateOfBirth: '1995-09-18',
    gender: 'Female',
    address: '303 Cedar Rd, Lakeside, USA',
    emergencyContact: '+1 (555) 432-1098',
    bloodType: 'A+',
    allergies: ['Latex', 'Eggs'],
    medicalHistory: ['Hypothyroidism'],
  },
  {
    id: '7',
    name: 'James Miller',
    email: 'james.m@example.com',
    phone: '+1 (555) 789-0123',
    dateOfBirth: '1975-04-25',
    gender: 'Male',
    address: '404 Elm St, Mountainview, USA',
    emergencyContact: '+1 (555) 321-0987',
    bloodType: 'B-',
    allergies: ['Peanuts'],
    medicalHistory: ['Arthritis', 'Hypertension'],
  },
  {
    id: '8',
    name: 'Olivia Brown',
    email: 'olivia.b@example.com',
    phone: '+1 (555) 890-1234',
    dateOfBirth: '1988-08-09',
    gender: 'Female',
    address: '505 Walnut Ave, Seaside, USA',
    emergencyContact: '+1 (555) 210-9876',
    bloodType: 'O+',
    allergies: ['Bee stings', 'Dairy'],
    medicalHistory: ['Asthma'],
  },
  {
    id: '9',
    name: 'Michael Davis',
    email: 'm.davis@example.com',
    phone: '+1 (555) 901-2345',
    dateOfBirth: '1991-01-12',
    gender: 'Male',
    address: '606 Spruce St, Valleytown, USA',
    emergencyContact: '+1 (555) 109-8765',
    bloodType: 'AB-',
    allergies: ['Penicillin'],
    medicalHistory: ['Ulcerative Colitis'],
  },
  {
    id: '10',
    name: 'Isabella Taylor',
    email: 'i.taylor@example.com',
    phone: '+1 (555) 012-3456',
    dateOfBirth: '1993-10-27',
    gender: 'Female',
    address: '707 Fir Ln, Parkville, USA',
    emergencyContact: '+1 (555) 098-7654',
    bloodType: 'A+',
    allergies: ['Soy', 'Wheat'],
    medicalHistory: ['Depression', 'Fibromyalgia'],
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    patientId: '1',
    patientName: 'John Smith',
    date: '2024-12-15',
    time: '09:00',
    type: 'Checkup',
    status: 'Scheduled',
    dentist: 'Dr. Sarah Johnson',
    notes: 'Regular 6-month checkup',
    duration: 45,
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Emma Wilson',
    date: '2024-12-15',
    time: '10:00',
    type: 'Filling',
    status: 'Scheduled',
    dentist: 'Dr. Michael Chen',
    notes: 'Cavity in lower left molar',
    duration: 60,
  },
  {
    id: '3',
    patientId: '3',
    patientName: 'Robert Chen',
    date: '2024-12-15',
    time: '11:30',
    type: 'Root Canal',
    status: 'Scheduled',
    dentist: 'Dr. Sarah Johnson',
    notes: 'Root canal treatment - session 2/3',
    duration: 90,
  },
  {
    id: '4',
    patientId: '4',
    patientName: 'Maria Garcia',
    date: '2024-12-15',
    time: '14:00',
    type: 'Cleaning',
    status: 'Completed',
    dentist: 'Dr. Lisa Rodriguez',
    notes: 'Regular cleaning, good oral hygiene',
    duration: 45,
  },
  {
    id: '5',
    patientId: '5',
    patientName: 'David Kim',
    date: '2024-12-16',
    time: '08:30',
    type: 'Extraction',
    status: 'Scheduled',
    dentist: 'Dr. Michael Chen',
    notes: 'Wisdom tooth extraction',
    duration: 75,
  },
  {
    id: '6',
    patientId: '6',
    patientName: 'Sophia Patel',
    date: '2024-12-16',
    time: '10:15',
    type: 'Consultation',
    status: 'Scheduled',
    dentist: 'Dr. Sarah Johnson',
    notes: 'Consultation for dental procedure',
    duration: 90,
  },
  {
    id: '7',
    patientId: '7',
    patientName: 'James Miller',
    date: '2024-12-16',
    time: '13:45',
    type: 'Consultation',
    status: 'Scheduled',
    dentist: 'Dr. Lisa Rodriguez',
    notes: 'Consult for dental implants',
    duration: 30,
  },
  {
    id: '8',
    patientId: '8',
    patientName: 'Olivia Brown',
    date: '2024-12-17',
    time: '09:45',
    type: 'Checkup',
    status: 'Cancelled',
    dentist: 'Dr. Michael Chen',
    notes: 'Monthly checkup - patient rescheduled',
    duration: 40,
  },
  {
    id: '9',
    patientId: '9',
    patientName: 'Michael Davis',
    date: '2024-12-17',
    time: '11:00',
    type: 'Extraction',
    status: 'Scheduled',
    dentist: 'Dr. Sarah Johnson',
    notes: 'Emergency tooth extraction due to pain',
    duration: 60,
  },
  {
    id: '10',
    patientId: '10',
    patientName: 'Isabella Taylor',
    date: '2024-12-17',
    time: '15:30',
    type: 'Cleaning',
    status: 'Scheduled',
    dentist: 'Dr. Lisa Rodriguez',
    notes: 'Professional teeth cleaning',
    duration: 60,
  },
  {
    id: '11',
    patientId: '1',
    patientName: 'John Smith',
    date: '2024-12-18',
    time: '10:00',
    type: 'Checkup',
    status: 'No-show',
    dentist: 'Dr. Sarah Johnson',
    notes: 'Follow-up on previous filling',
    duration: 30,
  },
  {
    id: '12',
    patientId: '3',
    patientName: 'Robert Chen',
    date: '2024-12-18',
    time: '14:15',
    type: 'Root Canal',
    status: 'Completed',
    dentist: 'Dr. Sarah Johnson',
    notes: 'Root canal treatment - final session',
    duration: 90,
  },
  {
    id: '13',
    patientId: '2',
    patientName: 'Emma Wilson',
    date: '2024-12-19',
    time: '13:00',
    type: 'Filling',
    status: 'Scheduled',
    dentist: 'Dr. Michael Chen',
    notes: 'Second filling needed',
    duration: 45,
  },
  {
    id: '14',
    patientId: '4',
    patientName: 'Maria Garcia',
    date: '2024-12-19',
    time: '15:30',
    type: 'Checkup',
    status: 'Scheduled',
    dentist: 'Dr. Lisa Rodriguez',
    notes: 'Post-whitening checkup',
    duration: 30,
  },
];

export const mockDentalRecords: DentalRecord[] = [
  {
      id: '1',
      patientId: '1',
      date: '2024-06-15',
      procedure: 'Dental Cleaning',
      notes: 'Mild plaque buildup, good oral hygiene',
      dentist: 'Dr. Sarah Johnson',
      cost: 120,
      xray: 'panoramic_20240615.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '2',
      patientId: '1',
      date: '2024-03-10',
      procedure: 'Dental Filling',
      notes: 'Composite filling on tooth #14, no complications',
      dentist: 'Dr. Michael Chen',
      cost: 180,
      xray: 'bitewing_20240310.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '3',
      patientId: '2',
      date: '2024-08-22',
      procedure: 'Comprehensive Exam',
      notes: 'Full mouth examination',
      dentist: 'Dr. Lisa Rodriguez',
      cost: 150,
      xray: 'fullmouth_20240822.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '4',
      patientId: '3',
      date: '2024-11-05',
      procedure: 'Root Canal',
      notes: 'Initial root canal treatment on tooth #30',
      dentist: 'Dr. Sarah Johnson',
      cost: 850,
      xray: 'periapical_20241105.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '5',
      patientId: '4',
      date: '2024-09-18',
      procedure: 'Teeth Whitening',
      notes: 'Professional whitening, excellent results',
      dentist: 'Dr. Lisa Rodriguez',
      cost: 350,
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '6',
      patientId: '5',
      date: '2024-07-30',
      procedure: 'Wisdom Tooth Consultation',
      notes: 'X-rays show impacted wisdom teeth',
      dentist: 'Dr. Michael Chen',
      cost: 95,
      xray: 'panoramic_20240730.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '7',
      patientId: '6',
      date: '2024-10-12',
      procedure: 'Dental Crown',
      notes: 'Tooth #19 prepared for permanent crown',
      dentist: 'Dr. Sarah Johnson',
      cost: 1100,
      xray: 'prep_20241012.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '8',
      patientId: '7',
      date: '2024-05-08',
      procedure: 'Deep Cleaning',
      notes: 'Deep cleaning for moderate gum disease',
      dentist: 'Dr. Lisa Rodriguez',
      cost: 400,
      xray: 'periodontal_20240508.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '9',
      patientId: '8',
      date: '2024-11-28',
      procedure: 'Braces Installation',
      notes: 'Full metal braces installed, good alignment',
      dentist: 'Dr. Michael Chen',
      cost: 4500,
      xray: 'cephalometric_20241128.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '10',
      patientId: '9',
      date: '2024-08-05',
      procedure: 'Emergency Extraction',
      notes: 'Infected tooth #3 extracted, antibiotics prescribed',
      dentist: 'Dr. Sarah Johnson',
      cost: 250,
      xray: 'extraction_20240805.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '11',
      patientId: '10',
      date: '2024-09-25',
      procedure: 'Dental Implant Consultation',
      notes: 'Evaluation for implant on tooth #9',
      dentist: 'Dr. Lisa Rodriguez',
      cost: 120,
      xray: 'implant_plan_20240925.jpg',
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
  {
      id: '12',
      patientId: '2',
      date: '2024-12-01',
      procedure: 'Fluoride Treatment',
      notes: 'Professional fluoride application',
      dentist: 'Dr. Lisa Rodriguez',
      cost: 75,
      tooth: undefined,
      type: undefined,
      doctor: undefined,
      paid: false,
      documents: []
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'Dental Checkup',
    description: 'Comprehensive oral examination',
    duration: 30,
    price: 80,
    category: 'Preventive',
  },
  {
    id: '2',
    name: 'Dental Cleaning',
    description: 'Professional teeth cleaning and polishing',
    duration: 45,
    price: 120,
    category: 'Preventive',
  },
  {
    id: '3',
    name: 'Teeth Whitening',
    description: 'Professional in-office teeth whitening',
    duration: 90,
    price: 350,
    category: 'Cosmetic',
  },
  {
    id: '4',
    name: 'Dental Filling',
    description: 'Composite resin filling for cavities',
    duration: 60,
    price: 150,
    category: 'Restorative',
  },
  {
    id: '5',
    name: 'Root Canal Therapy',
    description: 'Treatment for infected tooth pulp',
    duration: 90,
    price: 850,
    category: 'Restorative',
  },
  {
    id: '6',
    name: 'Dental Crown',
    description: 'Porcelain crown for damaged teeth',
    duration: 120,
    price: 1100,
    category: 'Restorative',
  },
  {
    id: '7',
    name: 'Tooth Extraction',
    description: 'Surgical removal of problematic teeth',
    duration: 60,
    price: 200,
    category: 'Emergency',
  },
  {
    id: '8',
    name: 'Dental Implant',
    description: 'Titanium implant with crown',
    duration: 180,
    price: 3000,
    category: 'Restorative',
  },
  {
    id: '9',
    name: 'Braces Consultation',
    description: 'Orthodontic evaluation and treatment plan',
    duration: 45,
    price: 95,
    category: 'Preventive',
  },
  {
    id: '10',
    name: 'Dental Bridge',
    description: 'Fixed bridge to replace missing teeth',
    duration: 150,
    price: 2500,
    category: 'Restorative',
  },
  {
    id: '11',
    name: 'Emergency Visit',
    description: 'Urgent dental care for pain or trauma',
    duration: 30,
    price: 125,
    category: 'Emergency',
  },
  {
    id: '12',
    name: 'Fluoride Treatment',
    description: 'Professional fluoride application',
    duration: 15,
    price: 75,
    category: 'Preventive',
  },
  {
    id: '13',
    name: 'Veneers Consultation',
    description: 'Consultation for dental veneers',
    duration: 60,
    price: 100,
    category: 'Cosmetic',
  },
  {
    id: '14',
    name: 'Dentures Fitting',
    description: 'Custom fitting for dentures',
    duration: 90,
    price: 500,
    category: 'Restorative',
  },
  {
    id: '15',
    name: 'Gum Treatment',
    description: 'Treatment for gum disease',
    duration: 60,
    price: 300,
    category: 'Preventive',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@clinic.com',
    role: 'admin',
    avatar: '/avatars/admin.jpg',
  },
  {
    id: '2',
    name: 'Dr. Sarah Johnson',
    email: 'sarah@clinic.com',
    role: 'dentist',
    avatar: '/avatars/dentist1.jpg',
  },
  {
    id: '3',
    name: 'Dr. Michael Chen',
    email: 'michael@clinic.com',
    role: 'dentist',
    avatar: '/avatars/dentist2.jpg',
  },
  {
    id: '4',
    name: 'Dr. Lisa Rodriguez',
    email: 'lisa@clinic.com',
    role: 'dentist',
    avatar: '/avatars/dentist3.jpg',
  },
  {
    id: '5',
    name: 'Jennifer Wilson',
    email: 'jennifer@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient1.jpg',
  },
  {
    id: '6',
    name: 'Robert Thompson',
    email: 'robert@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient2.jpg',
  },
  {
    id: '7',
    name: 'Amanda Lee',
    email: 'amanda@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient3.jpg',
  },
  {
    id: '8',
    name: 'Brian Carter',
    email: 'brian@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient4.jpg',
  },
  {
    id: '9',
    name: 'Emily Davis',
    email: 'emily@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient5.jpg',
  },
  {
    id: '10',
    name: 'Carlos Martinez',
    email: 'carlos@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient6.jpg',
  },
  {
    id: '11',
    name: 'Thomas Wilson',
    email: 'thomas@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient7.jpg',
  },
  {
    id: '12',
    name: 'Sophia Patel',
    email: 'sophia@clinic.com',
    role: 'patient',
    avatar: '/avatars/patient8.jpg',
  },
];